### ISSUE TITLE
Pairing mode doesn't work on QC35 II

### ISSUE THREAD

**Issue by Bezowski** [airvzxf/bose-connect-app-linux#10]
Hi, I can't get pairing mode working using "-p on" or "--pairing=on". All the other options are working though. 

I have the QC35 II firmware 4.8.1.

Thanks.

Edit: just noticed when trying to set pairing mode it returns the message "Invalid pairing argument: on"

**Comment by airvzxf** [comment]
@Bezowski, could you check this new version (last commit in main branch: 2cf59f5d2ba11bbfc4736de0c56601329f003737)?

Note: It is interesting because this bug that existed for years (maybe the 3 years), but nobody detected, neither me in my tests. Thank you for taking the time and effort to use this Linux package.

**Comment by Bezowski** [comment]
Yes it's working now, thanks for fixing it. I need to use this to pair new devices because the hardware switch on my headphones is broken.

**Comment by airvzxf** [comment]
It makes sense, usually, I use the physical button to do all of it.

If you find more bugs or have a wishlist (features), you are welcome to add in the issue tracker.
